INSERT INTO CUSTOMER
(USERNAME, EMAIL, LOCATION, NAME, FOLLOWER_COUNT, FOLLOWERS, FOLLOWING, FOLLOWING_COUNT)
VALUES
('karomo', 'karomo@gmail.com', 'Nairobi', 'Joe karomo',25,'famous','kidding',23);

INSERT INTO CUSTOMER
(USERNAME, EMAIL, LOCATION, NAME, FOLLOWER_COUNT, FOLLOWERS, FOLLOWING, FOLLOWING_COUNT)
VALUES
('onyango', 'onyango@gmail.com', 'Kisumu', 'Felix karomo',25,'famous','kidding',23);

INSERT INTO CUSTOMER
(USERNAME, EMAIL, LOCATION, NAME, FOLLOWER_COUNT, FOLLOWERS, FOLLOWING, FOLLOWING_COUNT)
VALUES
('Mutiso', 'Mutiso@gmail.com', 'Machakos', 'Brian Mutiso',25,'famous','kidding',23);


INSERT INTO CUSTOMER
(USERNAME, EMAIL, LOCATION, NAME, FOLLOWER_COUNT, FOLLOWERS, FOLLOWING, FOLLOWING_COUNT)
VALUES
('Kamea', 'Kamea@gmail.com', 'Nairobi', 'Henry Kamea',25,'famous','kidding',23);


INSERT INTO CUSTOMER
(USERNAME, EMAIL, LOCATION, NAME, FOLLOWER_COUNT, FOLLOWERS, FOLLOWING, FOLLOWING_COUNT)
VALUES
('Shosho', 'Shosho@gmail.com', 'Kinangop', 'Mimi Shosho',25,'famous','kidding',23);



